### ISSUE TITLE
Discuss which gems to use

### ISSUE THREAD

**Issue by krmbzds** [kilavus/kilavus-platform#2]
Gems selected for the **0.1.0** miletstone:

``` rb
gem 'haml-rails', '~> 0.4'
gem 'bootstrap-sass', '~> 2.3.2.2'
```

**Comment by krmbzds** [comment]
We've already done this; noting it down for the record:

``` rb
gem 'haml-rails', '~> 0.4'
```

**Comment by besirkurtulmus** [comment]
Should we add the bootstrap gem below?

``` rb
gem 'bootstrap-sass', '~> 2.3.2.2'
```

**Comment by krmbzds** [comment]
Looks like a good choice, we could also use this [blog post](http://blog.robertosoares.me/blog/2012/08/17/integrating-twitter-bootstrap-with-ruby-on-rails/) as a guide.

**Comment by krmbzds** [comment]
For forms, we can [simple_form](https://github.com/plataformatec/simple_form) and [rails_bootstrap_navbar](https://github.com/julescopeland/Rails-Bootstrap-Navbar):

``` rb
gem 'simple_form', '~> 3.0.0'
gem 'rails_bootstrap_navbar'
```

---

Also, as mentioned in the blog post we can use [these](https://gist.github.com/3344628) bootstrap flash message helpers.
I [forked](https://gist.github.com/krmbzds/7253855) and converted the `erb` files to `haml`.

---

Additionally, [will_paginate](https://github.com/mislav/will_paginate) gem along with [bootstrap-will_paginate](https://github.com/yrgoldteeth/bootstrap-will_paginate) seems like a good way to go.

``` rb
gem 'will_paginate', '~> 3.0'
gem 'bootstrap-will_paginate'
```
